language: node_js
node_js:
  - lts/*
dist: trusty
sudo: required

branches:
  only:
    - master

cache:
  directories:
    - '$HOME/.npm'

before_script:
  - npm install -g @angular/cli

script:
  - npm run lint
  - ng build --prod --base-href https://R-A-S.github.io/angular-book-store/
deploy:
  provider: pages
  skip_cleanup: true
  token: $GITHUB_TOKEN
  local_dir: dist/angular-book-store
  keep_history: true
  on:
    branch: master
notifications:
  email: false
