#dist: trusty
language: node_js
node_js:
  - lts/*
install:
  - npm ci
cache:
  directories:
    - "$HOME/.npm"
branches:
  only:
    - master
script:
  - npm run lint
  - npm run build
deploy:
  provider: pages
  skip_cleanup: true
  token: $GITHUB_TOKEN
  local_dir: dist/angular-book-store
  keep_history: true
  on:
    branch: master
notifications:
  email: false
